### ISSUE TITLE
Umbrella Ticket (5/26/2021)

### ISSUE THREAD

**Issue by KrispyKremeSavage** [zenxha/kpop#19]
Individual Tickets:
- [x] [CSS revision](https://github.com/zenxha/kpop/issues/7#issue-892260011) (Chris R)
- [x] [Easter egg](https://github.com/zenxha/kpop/issues/14#issue-892350884) (Devam S)
- [x] [About the Creators](https://github.com/zenxha/kpop/projects/2#card-62294965) (Charlie Z)
- [x] [Review page](https://github.com/zenxha/kpop/issues/17#issue-892355420) (Eshaan P)
- [x] [Playlist submission form](https://github.com/zenxha/kpop/issues/6#issue-892259168) (Komay S)

[Video Script](https://docs.google.com/document/d/1f1gv1DngebqykOswj5ijAOqdSo4twL9xNnzUNcnDBYA/edit)
[runtime link](http://rubinfamily.dyndns.org:5000/)
